---
title: "Ayudantía EPG3308"
subtitle: "EPG3308 - Computación Estadística"
# autor: "Tu nombre"
date: "`r format(Sys.Date(), '%d de %B, %Y')`"
output: 
    html_document:
        toc: true
        toc_float:
          collapsed: false
          smooth_scroll: false
        theme:
            bg: '#202123'      # Color de fondo
            fg: '#B8BCC2'      # Color fuente y lineas.
            primary: '#EA80FC' # Resaltado
            base_font: !expr bslib::font_google('Patrick Hand')
            code_font: !expr bslib::font_google('Fira Code')
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo      = TRUE,
                      message   = FALSE,
                      warning   = FALSE,
                      comment   = NA,
                      fig.align = 'center')

# Escribe los packages que usarás aquí:

require(ayudantia.epg3308)
```

## Pregunta 1

### Pregunta 1.1

```{r}
# Escribe tu código aquí
```

## Pregunta 2

### Pregunta 2.1 

```{r}
# Escribe tu código aquí
```

## Pregunta 3

### Pregunta 3.1

```{r}
# Escribe tu código aquí
```

